#If you do not need to run the pod on all nodes,
#we can in the <spec.template.spec> section add the
#<nodeSelector> with the label of the target nodes

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-monitor
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: mon-cnt
        image: terezabisharyan/monitoring
